---
version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/ruby:2.6.2-node
    steps:
      # Machine Setup
      - checkout

      # install pdf latex package
      - run: sudo apt-get install texlive -y

      # build pdf
      - run: pdflatex resume.tex

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          context: aws-cowholio4
