---
version: 2
jobs:
  deploy:
    parallelism: 1
    docker:
      - image: circleci/python:3.8.1
    steps:
      # Machine Setup
      - checkout

      # install pdf latex package
      - run: sudo apt-get update
      - run: sudo apt-get install texlive -y

      # build pdf
      - run: pdflatex resume.tex

      # deploy
      - run: pip install awscli --upgrade --user
      - run: aws s3 cp resume.pdf s3://www-cowholio4-com/

workflows:
  version: 2
  publish:
    jobs:
      - deploy:
          context: aws-cowholio4
          filters:
            branches:
              only: master
